package com.magic.crm.user.entity;


/**
 * Data Bean Class<br>
 * <br>
 * Autogenerated on 03/17/2003 10:06:41<br>
 * &nbsp;&nbsp;&nbsp; table = "roleright"
*
* @author Generator
*/
public class RoleRight implements java.io.Serializable {



   /**
    * The roleId attribute.
   */
   protected String RoleID = null;

   /**
    * Gets the roleId value.
   */
   public String getRoleID() {
      return RoleID;
   }

   /**
    * Sets the roleId value.
   */
   public void setRoleID(String roleId) {
      this.RoleID = roleId;
   }

   /**
    * The rightId attribute.
   */
   protected java.math.BigDecimal rightId = null;

   /**
    * Gets the rightId value.
   */
   public java.math.BigDecimal getRightId() {
      return rightId;
   }

   /**
    * Sets the rightId value.
   */
   public void setRightId(java.math.BigDecimal rightId) {
      this.rightId = rightId;
   }

   public String toString() {
      StringBuffer results = new StringBuffer();

      results.append(getClass().getName() + "\n");
      results.append("\troleId=" + RoleID + "\n");
      results.append("\trightId=" + rightId + "\n");

      return results.toString();
   }


}
