package com.magic.crm.user.entity;

import java.math.*;

/**
 * Data Bean Class<br>
 * <br>
 * Autogenerated on 03/17/2003 10:06:41<br>
 * &nbsp;&nbsp;&nbsp; table = "userrole"
*
* @author Generator
*/
public class UserRole implements java.io.Serializable {


   /**
    * The roleId attribute.
   */
   protected String roleId = null;

   /**
    * Gets the roleId value.
   */
   public String getRoleId() {
      return roleId;
   }

   /**
    * Sets the roleId value.
   */
   public void setRoleId(String roleId) {
      this.roleId = roleId;
   }

   /**
    * The id attribute.
   */
   protected String userId = null;

   /**
    * Gets the id value.
   */
   public String getUserId() {
      return userId;
   }

   /**
    * Sets the id value.
   */
   public void setUserId(String userId) {
      this.userId = userId;
   }

   public String toString() {
      StringBuffer results = new StringBuffer();

      results.append(getClass().getName() + "\n");
      results.append("\troleId=" + roleId + "\n");
      results.append("\tid=" + userId + "\n");

      return results.toString();
   }


}
