package com.magic.crm.product.form;

import com.magic.crm.common.pager.PagerForm;
/**
 * <code>ActionForm</code> Class<br>
 * <br>
 * Autogenerated on 02/19/2005 04:39:38<br>
 * &nbsp;&nbsp;&nbsp; table = "PROVIDERS"
*
* @author Generator
*/
public class ProviderForm extends PagerForm 
     implements java.io.Serializable {

	   
	   /**
	    * The providerID attribute.
	   */
	   protected String pro_no = "";
	   
	   /**
	    * Gets the providerID value.
	   */
	   public String getPro_no() {
	      return pro_no;
	   }
	   
	   /**
	    * Sets the providerID value.
	   */
	   public void setPro_no(String ipro_no) {
	      this.pro_no = ipro_no;
	   }

	   /**
	    * The providerName attribute.
	   */
	   protected String providerName = null;
	   
	   /**
	    * Gets the providerName value.
	   */
	   public String getProviderName() {
	      return providerName;
	   }
	   
	   /**
	    * Sets the providerName value.
	   */
	   public void setProviderName(String providerName) {
	      this.providerName = providerName;
	   }
	   
	   /**
	    * The providerAddress attribute.
	   */
	   protected java.lang.String providerAddress = null;
	   
	   /**
	    * Gets the providerAddress value.
	   */
	   public java.lang.String getProviderAddress() {
	      return providerAddress;
	   }
	   
	   /**
	    * Sets the providerAddress value.
	   */
	   public void setProviderAddress(java.lang.String providerAddress) {
	      this.providerAddress = providerAddress;
	   }

	   /**
	    * The goodsAdd attribute.
	   */
	   protected String goodsAdd = null;
	   
	   /**
	    * Gets the goodsAdd value.
	   */
	   public String getGoodsAdd() {
	      return goodsAdd;
	   }
	   
	   /**
	    * Sets the goodsAdd value.
	   */
	   public void setGoodsAdd(String goodsAdd) {
	      this.goodsAdd = goodsAdd;
	   }

	   /**
	    * The moneyDays attribute.
	   */
	   protected float moneyDays = 0.0f;
	   
	   /**
	    * Gets the moneyDays value.
	   */
	   public float getMoneyDays() {
	      return moneyDays;
	   }
	   
	   /**
	    * Sets the moneyDays value.
	   */
	   public void setMoneyDays(float moneyDays) {
	      this.moneyDays = moneyDays;
	   }

	   /**
	    * The pickUp attribute.
	   */
	   protected String pickUp = null;
	   
	   /**
	    * Gets the pickUp value.
	   */
	   public String getPickUp() {
	      return pickUp;
	   }
	   
	   /**
	    * Sets the pickUp value.
	   */
	   public void setPickUp(String pickUp) {
	      this.pickUp = pickUp;
	   }

	   /**
	    * The payDays attribute.
	   */
	   protected float payDays = 0.0f;
	   
	   /**
	    * Gets the payDays value.
	   */
	   public float getPayDays() {
	      return payDays;
	   }
	   
	   /**
	    * Sets the payDays value.
	   */
	   public void setPayDays(float payDays) {
	      this.payDays = payDays;
	   }

	   /**
	    * The cooperate attribute.
	   */
	   protected String cooperate = null;
	   
	   /**
	    * Gets the cooperate value.
	   */
	   public String getCooperate() {
	      return cooperate;
	   }
	   
	   /**
	    * Sets the cooperate value.
	   */
	   public void setCooperate(String cooperate) {
	      this.cooperate = cooperate;
	   }

	   /**
	    * The returnPolicy attribute.
	   */
	   protected String returnPolicy = null;
	   
	   /**
	    * Gets the returnPolicy value.
	   */
	   public String getReturnPolicy() {
	      return returnPolicy;
	   }
	   
	   /**
	    * Sets the returnPolicy value.
	   */
	   public void setReturnPolicy(String returnPolicy) {
	      this.returnPolicy = returnPolicy;
	   }

	   /**
	    * The returnBit attribute.
	   */
	   protected float returnBit = 0.0f;
	   
	   /**
	    * Gets the returnBit value.
	   */
	   public float getReturnBit() {
	      return returnBit;
	   }
	   
	   /**
	    * Sets the returnBit value.
	   */
	   public void setReturnBit(float returnBit) {
	      this.returnBit = returnBit;
	   }

	   /**
	    * The ProviderManager attribute.
	   */
	   protected String ProviderManager = null;
	   
	   /**
	    * Gets the ProviderManager value.
	   */
	   public String getProviderManager() {
	      return ProviderManager;
	   }
	   
	   /**
	    * Sets the ProviderManager value.
	   */
	   public void setProviderManager(String ProviderManager) {
	      this.ProviderManager = ProviderManager;
	   }

	   /**
	    * The stockProtect attribute.
	   */
	   protected float stockProtect = 0.0f;
	   
	   /**
	    * Gets the stockProtect value.
	   */
	   public float getStockProtect() {
	      return stockProtect;
	   }
	   
	   /**
	    * Sets the stockProtect value.
	   */
	   public void setStockProtect(float stockProtect) {
	      this.stockProtect = stockProtect;
	   }

	   /**
	    * The priPtotect attribute.
	   */
	   protected float priPtotect = 0.0f;
	   
	   /**
	    * Gets the priPtotect value.
	   */
	   public float getPriPtotect() {
	      return priPtotect;
	   }
	   
	   /**
	    * Sets the priPtotect value.
	   */
	   public void setPriPtotect(float priPtotect) {
	      this.priPtotect = priPtotect;
	   }

	   /**
	    * The postAdd attribute.
	   */
	   protected String postAdd = "";
	   
	   /**
	    * Gets the postAdd value.
	   */
	   public String getPostAdd() {
	      return postAdd;
	   }
	   
	   /**
	    * Sets the postAdd value.
	   */
	   public void setPostAdd(String postAdd) {
	      this.postAdd = postAdd;
	   }

	   /**
	    * The purchase attribute.
	   */
	   protected String purchase = null;
	   
	   /**
	    * Gets the purchase value.
	   */
	   public String getPurchase() {
	      return purchase;
	   }
	   
	   /**
	    * Sets the purchase value.
	   */
	   public void setPurchase(String purchase) {
	      this.purchase = purchase;
	   }

	   /**
	    * The invocieType attribute.
	   */
	   protected String invocieType = null;
	   
	   /**
	    * Gets the invocieType value.
	   */
	   public String getInvocieType() {
	      return invocieType;
	   }
	   
	   /**
	    * Sets the invocieType value.
	   */
	   public void setInvocieType(String invocieType) {
	      this.invocieType = invocieType;
	   }

	   /**
	    * The connecter attribute.
	   */
	   protected String connecter = null;
	   
	   /**
	    * Gets the connecter value.
	   */
	   public String getConnecter() {
	      return connecter;
	   }
	   
	   /**
	    * Sets the connecter value.
	   */
	   public void setConnecter(String connecter) {
	      this.connecter = connecter;
	   }

	   /**
	    * The taxRate attribute.
	   */
	   protected float taxRate = 0.0f;
	   
	   /**
	    * Gets the taxRate value.
	   */
	   public float getTaxRate() {
	      return taxRate;
	   }
	   
	   /**
	    * Sets the taxRate value.
	   */
	   public void setTaxRate(float taxRate) {
	      this.taxRate = taxRate;
	   }

	   /**
	    * The province attribute.
	   */
	   protected String province = null;
	   
	   /**
	    * Gets the province value.
	   */
	   public String getProvince() {
	      return province;
	   }
	   
	   /**
	    * Sets the province value.
	   */
	   public void setProvince(String province) {
	      this.province = province;
	   }

	   /**
	    * The city attribute.
	   */
	   protected String city = null;
	   
	   /**
	    * Gets the city value.
	   */
	   public String getCity() {
	      return city;
	   }
	   
	   /**
	    * Sets the city value.
	   */
	   public void setCity(String city) {
	      this.city = city;
	   }

	   /**
	    * The providerZip attribute.
	   */
	   protected String providerZip = null;
	   
	   /**
	    * Gets the providerZip value.
	   */
	   public String getProviderZip() {
	      return providerZip;
	   }
	   
	   /**
	    * Sets the providerZip value.
	   */
	   public void setProviderZip(String providerZip) {
	      this.providerZip = providerZip;
	   }

	   /**
	    * The telZip attribute.
	   */
	   protected String telZip = null;
	   
	   /**
	    * Gets the telZip value.
	   */
	   public String getTelZip() {
	      return telZip;
	   }
	   
	   /**
	    * Sets the telZip value.
	   */
	   public void setTelZip(String telZip) {
	      this.telZip = telZip;
	   }

	   /**
	    * The telephone attribute.
	   */
	   protected String telephone = null;
	   
	   /**
	    * Gets the telephone value.
	   */
	   public String getTelephone() {
	      return telephone;
	   }
	   
	   /**
	    * Sets the telephone value.
	   */
	   public void setTelephone(String telephone) {
	      this.telephone = telephone;
	   }

	   /**
	    * The fax attribute.
	   */
	   protected String fax = null;
	   
	   /**
	    * Gets the fax value.
	   */
	   public String getFax() {
	      return fax;
	   }
	   
	   /**
	    * Sets the fax value.
	   */
	   public void setFax(String fax) {
	      this.fax = fax;
	   }

	   /**
	    * The email attribute.
	   */
	   protected String email = null;
	   
	   /**
	    * Gets the email value.
	   */
	   public String getEmail() {
	      return email;
	   }
	   
	   /**
	    * Sets the email value.
	   */
	   public void setEmail(String email) {
	      this.email = email;
	   }

	   /**
	    * The providerTitle attribute.
	   */
	   protected String providerTitle = null;
	   
	   /**
	    * Gets the providerTitle value.
	   */
	   public String getProviderTitle() {
	      return providerTitle;
	   }
	   
	   /**
	    * Sets the providerTitle value.
	   */
	   public void setProviderTitle(String providerTitle) {
	      this.providerTitle = providerTitle;
	   }

	   /**
	    * The providerCategory attribute.
	   */
	   protected String providerCategory = null;
	   
	   /**
	    * Gets the providerCategory value.
	   */
	   public String getProviderCategory() {
	      return providerCategory;
	   }
	   
	   /**
	    * Sets the providerCategory value.
	   */
	   public void setProviderCategory(String providerCategory) {
	      this.providerCategory = providerCategory;
	   }

	   /**
	    * The ID attribute.
	   */
	   protected String ID = null;
	   
	   /**
	    * Gets the ID value.
	   */
	   public String getID() {
	      return ID;
	   }
	   
	   /**
	    * Sets the ID value.
	   */
	   public void setID(String ID) {
	      this.ID = ID;
	   }

	   /**
	    * The telephone2 attribute.
	   */
	   protected String telephone2 = null;
	   
	   /**
	    * Gets the telephone2 value.
	   */
	   public String getTelephone2() {
	      return telephone2;
	   }
	   
	   /**
	    * Sets the telephone2 value.
	   */
	   public void setTelephone2(String telephone2) {
	      this.telephone2 = telephone2;
	   }

	   /**
	    * The comments attribute.
	   */
	   protected String comments = null;
	   
	   /**
	    * Gets the comments value.
	   */
	   public String getComments() {
	      return comments;
	   }
	   
	   /**
	    * Sets the comments value.
	   */
	   public void setComments(String comments) {
	      this.comments = comments;
	   }

	   public String toString() {
	      StringBuffer results = new StringBuffer();

	      results.append(getClass().getName() + "\n");
	      results.append("\tproviderID=" + pro_no + "\n");
	      results.append("\tproviderName=" + providerName + "\n");
	      results.append("\tproviderAddress=" + providerAddress + "\n");
	      results.append("\tgoodsAdd=" + goodsAdd + "\n");
	      results.append("\tmoneyDays=" + moneyDays + "\n");
	      results.append("\tpickUp=" + pickUp + "\n");
	      results.append("\tpayDays=" + payDays + "\n");
	      results.append("\tcooperate=" + cooperate + "\n");
	      results.append("\treturnPolicy=" + returnPolicy + "\n");
	      results.append("\treturnBit=" + returnBit + "\n");
	      results.append("\tProviderManager=" + ProviderManager + "\n");
	      results.append("\tstockProtect=" + stockProtect + "\n");
	      results.append("\tpriPtotect=" + priPtotect + "\n");
	      results.append("\tpostAdd=" + postAdd + "\n");
	      results.append("\tpurchase=" + purchase + "\n");
	      results.append("\tinvocieType=" + invocieType + "\n");
	      results.append("\tconnecter=" + connecter + "\n");
	      results.append("\ttaxRate=" + taxRate + "\n");
	      results.append("\tprovince=" + province + "\n");
	      results.append("\tcity=" + city + "\n");
	      results.append("\tproviderZip=" + providerZip + "\n");
	      results.append("\ttelZip=" + telZip + "\n");
	      results.append("\ttelephone=" + telephone + "\n");
	      results.append("\tfax=" + fax + "\n");
	      results.append("\temail=" + email + "\n");
	      results.append("\tproviderTitle=" + providerTitle + "\n");
	      results.append("\tproviderCategory=" + providerCategory + "\n");
	      results.append("\tID=" + ID + "\n");
	      results.append("\ttelephone2=" + telephone2 + "\n");
	      results.append("\tcomments=" + comments + "\n");

	      return results.toString();
	   }
   public void reset(org.apache.struts.action.ActionMapping mapping, javax.servlet.http.HttpServletRequest request) {
   	pro_no = "";
      providerName = null;
      providerAddress = null;
      goodsAdd = null;
      moneyDays = 0;
      pickUp = null;
      payDays = 0;
      cooperate = null;
      returnPolicy = null;
      returnBit = 0;
      ProviderManager = null;
      stockProtect = 0;
      priPtotect = 0;
      postAdd = "";
      purchase = null;
      invocieType = null;
      connecter = null;
      taxRate = 0;
      province = null;
      city = null;
      providerZip = null;
      telZip = null;
      telephone = null;
      fax = null;
      email = null;
      providerTitle = null;
      providerCategory = null;
      ID = null;
      telephone2 = null;
      comments = null;
   }




}
