package com.magic.crm.user.dao;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;

import com.magic.crm.user.entity.*;

/**
 * Jdbc Bean Class<br>
 * <br>
 * Autogenerated on 03/17/2003 10:36:03<br>
 * &nbsp;&nbsp;&nbsp; table = "userrole"
*
* @author Generator
*/
public class UserRoleDAO implements java.io.Serializable {

	 public Collection find(Connection con, com.magic.crm.user.entity.User info) throws SQLException {
      PreparedStatement pstmt = null;
			ResultSet rs = null;
			Collection userRoleCol = new ArrayList();

      try {
         String sQuery = "select id,roleId from crm_userrole where id=?";
         pstmt = con.prepareStatement(sQuery);
         pstmt.setString(1, info.getId());

         rs = pstmt.executeQuery();

         while(rs.next()) {

        		UserRole ur = new UserRole();

        		ur.setUserId(rs.getString(1));

        		ur.setRoleId(rs.getString(2));

        		userRoleCol.add(ur);

         }

       } catch (SQLException e) {
          throw e;
       } finally {
          if (pstmt != null)
             try { pstmt.close(); } catch (Exception e) {}
       }
       return userRoleCol;
   }

   public Collection find(Connection con, com.magic.crm.user.entity.Role info) throws SQLException {
      PreparedStatement pstmt = null;
			ResultSet rs = null;
			Collection userRoleCol = new ArrayList();

      try {
         String sQuery = "select id,roleId from crm_userrole where roleId=?";
         pstmt = con.prepareStatement(sQuery);
         pstmt.setString(1, info.getRoleID());

         rs = pstmt.executeQuery();

         while(rs.next()) {

        		UserRole ur = new UserRole();

        		ur.setUserId(rs.getString(1));

        		ur.setRoleId(rs.getString(2));

        		userRoleCol.add(ur);

         }

       } catch (SQLException e) {
          throw e;
       } finally {
          if (pstmt != null)
             try { pstmt.close(); } catch (Exception e) {}
       }
       return userRoleCol;
   }


   public void insert(Connection con, com.magic.crm.user.entity.UserRole info) throws SQLException {
      PreparedStatement pstmt = null;

      try {
         String sQuery = "INSERT INTO crm_userrole(roleId, id) VALUES(?, ?)";
         pstmt = con.prepareStatement(sQuery);

         pstmt.setString(1, info.getRoleId());
         pstmt.setString(2, info.getUserId());

         pstmt.execute();

       } catch (SQLException e) {
          throw e;
       } finally {
          if (pstmt != null)
             try { pstmt.close(); } catch (Exception e) {}
       }
   }


   public void delete(Connection con, com.magic.crm.user.entity.User info) throws SQLException {
      PreparedStatement pstmt = null;

      try {
         String sQuery = "DELETE from crm_userrole WHERE id=?";
         pstmt = con.prepareStatement(sQuery);
	       pstmt.setString(1,info.getId());

         pstmt.execute();

       } catch (SQLException e) {
          throw e;
       } finally {
          if (pstmt != null)
             try { pstmt.close(); } catch (Exception e) {}
       }
   }


}
