package com.magic.crm.product.entity;


/**
 * Data Bean Class<br>
 * <br>
 * Autogenerated on 01/28/2005 06:41:59<br>
 * &nbsp;&nbsp;&nbsp; table = "prd_items"
*
* @author Generator
*/
public class ProductCategory implements java.io.Serializable {

	/**
	 * The catalogID attribute.
	 */
	protected java.lang.String catalogID = null;
	   
	/**
	 * Gets the catalogID value.
	 */
	public java.lang.String getCatalogID() {
	      return catalogID;
	}
	   
	/**
	 * Sets the itemID value.
	 */
	public void setCatalogID(java.lang.String catalogID) {
	      this.catalogID = catalogID;
	}

	/**
	 * The itemID attribute.
	 */
	protected java.lang.String parentID = null;
	   
	/**
	 * Gets the itemID value.
	 */
	public java.lang.String getParentID() {
	      return parentID;
	}
	   
	/**
	 * Sets the itemID value.
	 */
	public void setParentID(java.lang.String parentID) {
	      this.parentID = parentID;
	} 
	
	/**
	 * The catalogLevel attribute.
	 */
	protected java.lang.String catalogLevel = null;
	   
	/**
	 * Gets the catalogLevel value.
	 */
	public java.lang.String getCatalogLevel() {
	      return catalogLevel;
	}
	   
	/**
	 * Sets the catalogLevel value.
	 */
	public void setCatalogLevel(java.lang.String catalogLevel) {
	      this.catalogLevel = catalogLevel;
	} 
	
	protected java.lang.String companyID = null;
	   
	/**
	 * Gets the companyID value.
	 */
	public java.lang.String getCompanyID() {
	      return companyID;
	}
	   
	/**
	 * Sets the companyID value.
	 */
	public void setCompanyID(java.lang.String companyID) {
	      this.companyID = companyID;
	} 
	
	protected java.lang.String isLeaf = null;
	   
	/**
	 * Gets the isLeaf value.
	 */
	public java.lang.String getIsLeaf() {
	      return companyID;
	}
	   
	/**
	 * Sets the isLeaf value.
	 */
	public void setIsLeaf(java.lang.String isLeaf) {
	      this.isLeaf = isLeaf;
	}
	
	protected java.lang.String catalogName = null;
	   
	/**
	 * Gets the isLeaf value.
	 */
	public java.lang.String getCatalogName() {
	      return catalogName;
	}
	   
	/**
	 * Sets the isLeaf value.
	 */
	public void setCatalogName(java.lang.String catalogName) {
	      this.catalogName = catalogName;
	} 
	
	protected java.lang.String catalogCode = null;
	   
	/**
	 * Gets the isLeaf value.
	 */
	public java.lang.String getCatalogCode() {
	      return catalogCode;
	}
	   
	/**
	 * Sets the isLeaf value.
	 */
	public void setCatalogCode(java.lang.String catalogCode) {
	      this.catalogCode = catalogCode;
	}
	
	protected java.lang.String description = null;
	   
	/**
	 * Gets the isLeaf value.
	 */
	public java.lang.String getDescription() {
	      return description;
	}
	   
	/**
	 * Sets the isLeaf value.
	 */
	public void setDescription(java.lang.String description) {
	      this.description = description;
	} 
	

   
}
