package com.magic.crm.product.entity;


/**
 * Data Bean Class<br>
 * <br>
 * Autogenerated on 02/15/2005 05:24:46<br>
 * &nbsp;&nbsp;&nbsp; table = "s_tax"
*
* @author Generator
*/
public class Tax implements java.io.Serializable {

   /**
    * The ID attribute.
   */
   protected int ID = 0;
   
   /**
    * Gets the ID value.
   */
   public int getID() {
      return ID;
   }
   
   /**
    * Sets the ID value.
   */
   public void setID(int ID) {
      this.ID = ID;
   }

   /**
    * The companyID attribute.
   */
   protected int companyID = 0;
   
   /**
    * Gets the companyID value.
   */
   public int getCompanyID() {
      return companyID;
   }
   
   /**
    * Sets the companyID value.
   */
   public void setCompanyID(int companyID) {
      this.companyID = companyID;
   }

   /**
    * The name attribute.
   */
   protected java.lang.String name = null;
   
   /**
    * Gets the name value.
   */
   public java.lang.String getName() {
      return name;
   }
   
   /**
    * Sets the name value.
   */
   public void setName(java.lang.String name) {
      this.name = name;
   }

   /**
    * The description attribute.
   */
   protected String description = null;
   
   /**
    * Gets the description value.
   */
   public String getDescription() {
      return description;
   }
   
   /**
    * Sets the description value.
   */
   public void setDescription(String description) {
      this.description = description;
   }

   /**
    * The tax attribute.
   */
   protected Number tax = null;
   
   /**
    * Gets the tax value.
   */
   public Number getTax() {
      return tax;
   }
   
   /**
    * Sets the tax value.
   */
   public void setTax(Number tax) {
      this.tax = tax;
   }

   /**
    * The taxType attribute.
   */
   protected String taxType = null;
   
   /**
    * Gets the taxType value.
   */
   public String getTaxType() {
      return taxType;
   }
   
   /**
    * Sets the taxType value.
   */
   public void setTaxType(String taxType) {
      this.taxType = taxType;
   }

   public String toString() {
      StringBuffer results = new StringBuffer();

      results.append(getClass().getName() + "\n");
      results.append("\tID=" + ID + "\n");
      results.append("\tcompanyID=" + companyID + "\n");
      results.append("\tname=" + name + "\n");
      results.append("\tdescription=" + description + "\n");
      results.append("\ttax=" + tax + "\n");
      results.append("\ttaxType=" + taxType + "\n");

      return results.toString();
   }


}
