package com.magic.crm.promotion.form;

import org.apache.struts.action.ActionForm;

/* 
 * this class is generated by codeGen 0.1 
 * create on Wed Aug 27 21:15:53 CST 2008
 * 
 * todo 
 */ 
public class PRD_PRICELIST_GIFTForm extends ActionForm{ 

	protected String item_name="";
	
	
	public String getItem_name() {
		return item_name;
	}
	public void setItem_name(String item_name) {
		this.item_name = item_name;
	}


	protected int id=0;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id=id;
	}


	protected int pricelist_id=0;
	public int getPricelist_id() {
		return pricelist_id;
	}
	public void setPricelist_id(int pricelist_id) {
		this.pricelist_id=pricelist_id;
	}


	protected String item_code="";
	public String getItem_code() {
		return item_code;
	}
	public void setItem_code(String item_code) {
		this.item_code=item_code;
	}


	protected double price=0;
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price=price;
	}


	protected int quantity=0;
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity=quantity;
	}


	protected int type=0;
	public int getType() {
		return type;
	}
	public void setType(int type) {
		this.type=type;
	}


	protected int status=0;
	public int getStatus() {
		return status;
	}
	public void setStatus(int status) {
		this.status=status;
	}

} 
