/* 
 * @author CodeGen 0.1 
 * create on Thu Sep 04 09:24:48 CST 2008
 * 
 * todo 
 */ 

package com.magic.crm.promotion.form;

import org.apache.struts.action.ActionForm;

/* 
 * this class is generated by codeGen 0.1 
 * create on Thu Sep 04 09:24:48 CST 2008
 * 
 * todo 
 */ 
public class S_catalog_editionForm extends ActionForm{ 

	protected int id=0;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id=id;
	}


	protected String name="";
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name=name;
	}


	protected String description="";
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description=description;
	}

} 