package com.magic.crm.award.form;

import java.math.*;

/**
 * <code>ActionForm</code> Class<br>
 * <br>
 * Autogenerated on 03/14/2003 01:39:32<br>
 * &nbsp;&nbsp;&nbsp; table = "users"
 *
 * @author Generator
 */
public class AwardForm extends org.apache.struts.validator.ValidatorForm
		implements java.io.Serializable {

	protected int id = 0;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	protected int status = 0;
	
	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}
	
	protected int memberID ;
	public int getMemberID(){
		return memberID;
	}
	public void setMemberID(int memberID){
		this.memberID= memberID;
	}
	
	
	protected double amountExp = 0;
	public double getAmountExp(){
		return amountExp;
	}
	public void setAmountExp(double amountExp){
		this.amountExp= amountExp;
	}
	
	protected int sellType = 0;
	
	/**
	 * @return Returns the sellType.
	 */
	public int getSellType() {
		return sellType;
	}
	/**
	 * @param sellType The sellType to set.
	 */
	public void setSellType(int sellType) {
		this.sellType = sellType;
	}
	protected String operatorName = null;
	
	/**
	 * @return Returns the operatorName.
	 */
	public String getOperatorName() {
		return operatorName;
	}
	/**
	 * @param operatorName The operatorName to set.
	 */
	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}
	public void reset(org.apache.struts.action.ActionMapping mapping,
			javax.servlet.http.HttpServletRequest request) {
		

	}
	

}
