package com.magic.crm.user.entity;

import java.util.Map;


/**
 * Data Bean Class<br>
 * <br>
 * Autogenerated on 03/17/2003 10:06:41<br>
 * &nbsp;&nbsp;&nbsp; table = "users"
*
* @author Generator
*/
public class User implements java.io.Serializable {

	 protected String id = null;
	 protected int COMPANY_ID =0;
	 public String NAME = null;
	 protected String PHONE=null;
	 protected String USERID=null;
	 protected String PWD=null;
	 protected int DEPARTMENT_ID=0;
	 protected int STATUS=0;
	 protected String EMAIL=null;
	 protected String TITLE=null;
	 protected String GENDER=null;
	 protected int EMPLOYEE_TYPE=0;
	 protected String MOBILE_PHONE=null;
	 protected String BP=null;
	 protected String PIC_URL=null;
	 protected java.util.Date CREATE_DATE=null;
	 protected int LOCATION_ID=0;
	 protected String EMPLOYEE_NUMBER=null;
	 protected int MANAGER_ID=0;
	 protected java.util.BitSet AccessRight=null;
	 protected Map fieldRights = null;
	 protected int logID=0;
	 protected String telno="";

	   public int getLogID(){
	    return logID;
	   }
	   public void setLogID(int logID) {
	    this.logID = logID;
	   }	 
	   public String getTelno() {
	      return telno;
	   }
	   public void setTelno(String telno) {
	      this.telno = telno;
	   }	 
   public String getId() {
      return id;
   }
   public void setId(String id) {
      this.id = id;
   }
   public String getNAME(){
    return NAME;
   }
   public void setNAME(String name) {
    this.NAME = name;
   }
   public int getCOMPANY_ID(){
    return COMPANY_ID;
   }
   public void setCOMPANY_ID(int pCOMPANY_ID) {
    this.COMPANY_ID = pCOMPANY_ID;
   }
   public String getPHONE(){
    return PHONE;
   }
   public void setPHONE(String pPHONE) {
    this.PHONE = pPHONE;
   }   
   public String getUSERID(){
    return USERID;
   }
   public void setUSERID(String pUSERID) {
    this.USERID = pUSERID;
   }  
   public String getPWD(){
    return PWD;
   }
   public void setPWD(String pPWD) {
    this.PWD = pPWD;
   }  
   public int getDEPARTMENT_ID(){
    return DEPARTMENT_ID;
   }
   public void setDEPARTMENT_ID(int pDEPARTMENT_ID) {
    this.DEPARTMENT_ID = pDEPARTMENT_ID;
   }  
   public int getSTATUS(){
    return STATUS;
   }
   public void setSTATUS(int pSTATUS) {
    this.STATUS = pSTATUS;
   }  
   public String getEMAIL(){
    return EMAIL;
   }
   public void setEMAIL(String pEMAIL) {
    this.EMAIL = pEMAIL;
   }  
                  
   public String getTITLE(){
    return TITLE;
   }
   public void setTITLE(String pTITLE) {
    this.TITLE = pTITLE;
   }  
   public String getGENDER(){
    return GENDER;
   }  
   public void setGENDER(String pGENDER) {
    this.GENDER = pGENDER;
   }  
   
   public int getEMPLOYEE_TYPE(){
    return EMPLOYEE_TYPE;
   }
   public void setEMPLOYEE_TYPE(int pEMPLOYEE_TYPE) {
    this.EMPLOYEE_TYPE = pEMPLOYEE_TYPE;
   }  
   public String getMOBILE_PHONE(){
    return MOBILE_PHONE;
   }
   public void setMOBILE_PHONE(String pMOBILE_PHONE) {
    this.MOBILE_PHONE = pMOBILE_PHONE;
   }  

   public String getBP(){
    return BP;
   }
   public void setBP(String pBP) {
    this.BP = pBP;
   }  
   public String getPIC_URL(){
    return PIC_URL;
   }
   public void setPIC_URL(String pPIC_URL) {
    this.PIC_URL = pPIC_URL;
   }  
  
   public java.util.Date getCREATE_DATE(){
    return CREATE_DATE;
   }
   public void setCREATE_DATE(java.util.Date pCREATE_DATE) {
    this.CREATE_DATE = pCREATE_DATE;
   }  
                                                                              
   public int getLOCATION_ID(){
    return LOCATION_ID;
   }
   public void setLOCATION_ID(int pLOCATION_ID) {
    this.LOCATION_ID = pLOCATION_ID;
   }  
   public String getEMPLOYEE_NUMBER(){
    return EMPLOYEE_NUMBER;
   }
   public void setEMPLOYEE_NUMBER(String pEMPLOYEE_NUMBER) {
    this.EMPLOYEE_NUMBER = pEMPLOYEE_NUMBER;
   }  
   public int getMANAGER_ID(){
    return MANAGER_ID;
   }
   public void setMANAGER_ID(int pMANAGER_ID) {
    this.MANAGER_ID = pMANAGER_ID;
   }     
   public java.util.BitSet getAccessRight() {
    return AccessRight;
 }
   public void setAccessRight(java.util.BitSet accessRight) {
    this.AccessRight = accessRight;
 }                                             
	


   
 /*
   public String toString() {
      StringBuffer results = new StringBuffer();

      results.append(getClass().getName() + "\n");
      results.append("\tid=" + id + "\n");
      results.append("\tuserName=" + userName + "\n");
      results.append("\tfirstName=" + firstName + "\n");
      results.append("\tlastName=" + lastName + "\n");
      results.append("\tmidName=" + midName + "\n");
      results.append("\taddress1=" + address1 + "\n");
      results.append("\taddress2=" + address2 + "\n");
      results.append("\tcity=" + city + "\n");
      results.append("\tstate=" + state + "\n");
      results.append("\tzip=" + zip + "\n");
      results.append("\tcountry=" + country + "\n");
      results.append("\temail=" + email + "\n");
      results.append("\thomePhone=" + homePhone + "\n");
      results.append("\tworkPhone=" + workPhone + "\n");
      results.append("\tfax=" + fax + "\n");
      results.append("\taccessRight=" + accessRight + "\n");
      results.append("\tpassword=" + password + "\n");
      results.append("\tDEPARTMENTID=" + DEPARTMENTID + "\n");
      results.append("\tMANAGERID=" + MANAGERID + "\n");

      return results.toString();
   }
  */

   
    /**
     * @return Returns the fieldRights.
     */
    public Map getFieldRights() {
        return fieldRights;
    }
    /**
     * @param fieldRights The fieldRights to set.
     */
    public void setFieldRights(Map fieldRights) {
        this.fieldRights = fieldRights;
    }
}
