package com.magic.crm.product.form;

import java.math.BigDecimal;
/**
 * <code>ActionForm</code> Class<br>
 * <br>
 * Autogenerated on 03/10/2005 01:53:42<br>
 * &nbsp;&nbsp;&nbsp; table = "prd_Item_Sets"
*
* @author Generator
*/
public class ProductSetItemForm extends org.apache.struts.action.ActionForm 
     implements java.io.Serializable {


   /**
    * The setItemID attribute.
   */
   protected java.lang.String setItemID = null;
   
   /**
    * Gets the setItemID value.
   */
   public java.lang.String getSetItemID() {
      return setItemID;
   }
   
   /**
    * Sets the setItemID value.
   */
   public void setSetItemID(java.lang.String setItemID) {
      this.setItemID = setItemID;
   }

   /**
    * The partItemID attribute.
   */
   protected java.lang.String partItemID = null;
   
   /**
    * Gets the partItemID value.
   */
   public java.lang.String getPartItemID() {
      return partItemID;
   }
   
   /**
    * Sets the partItemID value.
   */
   public void setPartItemID(java.lang.String partItemID) {
      this.partItemID = partItemID;
   }

   /**
    * The silverPrice attribute.
   */
   protected float silverPrice = 0f;
   
   /**
    * Gets the silverPrice value.
   */
   public float getSilverPrice() {
      return silverPrice;
   }
   
   /**
    * Sets the silverPrice value.
   */
   public void setSilverPrice(float silverPrice) {
      this.silverPrice = silverPrice;
   }

   /**
    * The godenPrice attribute.
   */
   protected float godenPrice = 0f;
   
   /**
    * Gets the godenPrice value.
   */
   public float getGodenPrice() {
      return godenPrice;
   }
   
   /**
    * Sets the godenPrice value.
   */
   public void setGodenPrice(float godenPrice) {
      this.godenPrice = godenPrice;
   }

   /**
    * The webPrice attribute.
   */
   protected float webPrice = 0f;
   
   /**
    * Gets the webPrice value.
   */
   public float getWebPrice() {
      return webPrice;
   }
   
   /**
    * Sets the webPrice value.
   */
   public void setWebPrice(float webPrice) {
      this.webPrice = webPrice;
   }

   /**
    * The id attribute.
   */
   protected BigDecimal id ;
   
   /**
    * Gets the id value.
   */
   public BigDecimal getId() {
      return id;
   }
   
   /**
    * Sets the id value.
   */
   public void setId(BigDecimal id) {
      this.id = id;
   }

   public void reset(org.apache.struts.action.ActionMapping mapping, javax.servlet.http.HttpServletRequest request) {
      setItemID = null;
      partItemID = null;
      silverPrice = 0f;
      godenPrice = 0f;
      webPrice = 0f;
      id = null;
   }

   public String toString() {
      StringBuffer results = new StringBuffer();

      results.append(getClass().getName() + "\n");
      results.append("\tsetItemID=" + setItemID + "\n");
      results.append("\tpartItemID=" + partItemID + "\n");
      results.append("\tsilverPrice=" + silverPrice + "\n");
      results.append("\tgodenPrice=" + godenPrice + "\n");
      results.append("\twebPrice=" + webPrice + "\n");
      results.append("\tid=" + id + "\n");

      return results.toString();
   }


}
