package com.magic.crm.product.form;

import java.util.ArrayList;

import org.apache.struts.action.ActionForm;
import org.apache.struts.util.LabelValueBean;

/**
 * <code>ActionForm</code> Class<br>
 * <br>
 * Autogenerated on 03/10/2005 01:53:42<br>
 * &nbsp;&nbsp;&nbsp; table = "prd_Item_Sets"
*
* @author Generator
*/
public class Product2SetForm extends Product2Form

     implements java.io.Serializable {

	
	public int getSet_id() {
		return set_id;
	}
	public void setSet_id(int set_id) {
		this.set_id = set_id;
	}
	public String getSet_item_code() {
		return set_item_code;
	}
	public void setSet_item_code(String set_item_code) {
		this.set_item_code = set_item_code;
	}
	public String getSet_item_name() {
		return set_item_name;
	}
	public void setSet_item_name(String set_item_name) {
		this.set_item_name = set_item_name;
	}
	public String getPart_item_code() {
		return part_item_code;
	}
	public void setPart_item_code(String part_item_code) {
		this.part_item_code = part_item_code;
	}
	public String getPart_item_name() {
		return part_item_name;
	}
	public void setPart_item_name(String part_item_name) {
		this.part_item_name = part_item_name;
	}
	public int getIs_optional() {
		return is_optional;
	}
	public void setIs_optional(int is_optional) {
		this.is_optional = is_optional;
	}
	public double getSale_price() {
		return sale_price;
	}
	public void setSale_price(double sale_price) {
		this.sale_price = sale_price;
	}
	public double getVip_price() {
		return vip_price;
	}
	public void setVip_price(double vip_price) {
		this.vip_price = vip_price;
	}
	public String getColor_code() {
		return color_code;
	}
	public void setColor_code(String color_code) {
		this.color_code = color_code;
	}
	public String getColor_name() {
		return color_name;
	}
	public void setColor_name(String color_name) {
		this.color_name = color_name;
	}
	
	ArrayList colors = new ArrayList();
	public ArrayList getColors() {
		return colors;
	}
	public void setColors(ArrayList colors) {
		this.colors = colors;
	}

	int set_id;
	String set_item_code;
	String set_item_name;
	String part_item_code;
	String part_item_name;
	String color_code;
	String color_name;
	int is_optional;
	double sale_price;
	double vip_price;
	String op_type;
	
	public String getOp_type() {
		return op_type;
	}
	public void setOp_type(String op_type) {
		this.op_type = op_type;
	}
  
}
