package com.magic.crm.product.form;


/**
 * <code>ActionForm</code> Class<br>
 * <br>
 * Autogenerated on 02/15/2005 05:24:46<br>
 * &nbsp;&nbsp;&nbsp; table = "s_tax"
*
* @author Generator
*/
public class TaxForm extends org.apache.struts.action.ActionForm 
     implements java.io.Serializable {


   /**
    * The ID attribute.
   */
   protected java.lang.String ID = null;
   
   /**
    * Gets the ID value.
   */
   public java.lang.String getID() {
      return ID;
   }
   
   /**
    * Sets the ID value.
   */
   public void setID(java.lang.String ID) {
      this.ID = ID;
   }

   /**
    * The companyID attribute.
   */
   protected java.lang.String companyID = null;
   
   /**
    * Gets the companyID value.
   */
   public java.lang.String getCompanyID() {
      return companyID;
   }
   
   /**
    * Sets the companyID value.
   */
   public void setCompanyID(java.lang.String companyID) {
      this.companyID = companyID;
   }

   /**
    * The name attribute.
   */
   protected java.lang.String name = null;
   
   /**
    * Gets the name value.
   */
   public java.lang.String getName() {
      return name;
   }
   
   /**
    * Sets the name value.
   */
   public void setName(java.lang.String name) {
      this.name = name;
   }

   /**
    * The description attribute.
   */
   protected java.lang.String description = null;
   
   /**
    * Gets the description value.
   */
   public java.lang.String getDescription() {
      return description;
   }
   
   /**
    * Sets the description value.
   */
   public void setDescription(java.lang.String description) {
      this.description = description;
   }

   /**
    * The tax attribute.
   */
   protected java.lang.String tax = null;
   
   /**
    * Gets the tax value.
   */
   public java.lang.String getTax() {
      return tax;
   }
   
   /**
    * Sets the tax value.
   */
   public void setTax(java.lang.String tax) {
      this.tax = tax;
   }

   /**
    * The taxType attribute.
   */
   protected java.lang.String taxType = null;
   
   /**
    * Gets the taxType value.
   */
   public java.lang.String getTaxType() {
      return taxType;
   }
   
   /**
    * Sets the taxType value.
   */
   public void setTaxType(java.lang.String taxType) {
      this.taxType = taxType;
   }

   public void reset(org.apache.struts.action.ActionMapping mapping, javax.servlet.http.HttpServletRequest request) {
      ID = null;
      companyID = null;
      name = null;
      description = null;
      tax = null;
      taxType = null;
   }

   public String toString() {
      StringBuffer results = new StringBuffer();

      results.append(getClass().getName() + "\n");
      results.append("\tID=" + ID + "\n");
      results.append("\tcompanyID=" + companyID + "\n");
      results.append("\tname=" + name + "\n");
      results.append("\tdescription=" + description + "\n");
      results.append("\ttax=" + tax + "\n");
      results.append("\ttaxType=" + taxType + "\n");

      return results.toString();
   }


}
