package com.magic.crm.user.form;


/**
 * <code>ActionForm</code> Class<br>
 * <br>
 * Autogenerated on 03/14/2003 01:39:31<br>
 * &nbsp;&nbsp;&nbsp; table = "rights"
*
* @author Generator
*/
public class RightForm extends org.apache.struts.action.ActionForm
     implements java.io.Serializable {


   /**
    * The rightId attribute.
   */
   protected java.math.BigDecimal rightId = null;

   /**
    * Gets the rightId value.
   */
   public java.math.BigDecimal getRightId() {
      return rightId;
   }

   /**
    * Sets the rightId value.
   */
   public void setRightId(java.math.BigDecimal rightId) {
      this.rightId = rightId;
   }
   /**
    * The rightId attribute.
   */
   protected java.math.BigDecimal parentId = null;

   /**
    * Gets the rightId value.
   */
   public java.math.BigDecimal getParentId() {
      return parentId;
   }

   /**
    * Sets the rightId value.
   */
   public void setParentId(java.math.BigDecimal parentId) {
      this.parentId = parentId;
   }
   /**
    * The rightName attribute.
   */
   protected java.lang.String rightName = null;

   /**
    * Gets the rightName value.
   */
   public java.lang.String getRightName() {
      return rightName;
   }

   /**
    * Sets the rightName value.
   */
   public void setRightName(java.lang.String rightName) {
      this.rightName = rightName;
   }

// *************************************************
// *************************************************
    protected java.lang.String id = null;

    /**
     * Gets the rightName value.
    */
    public java.lang.String getID() {
       return id;
    }

    /**
     * Sets the rightName value.
    */
    public void setID(java.lang.String i) {
       this.id = i;
    }  
   public void reset(org.apache.struts.action.ActionMapping mapping, javax.servlet.http.HttpServletRequest request) {
      rightId = null;
      rightName = null;
      id=null;
   }

   public String toString() {
      StringBuffer results = new StringBuffer();

      results.append(getClass().getName() + "\n");
      results.append("\trightId=" + rightId + "\n");
      results.append("\trightName=" + rightName + "\n");

      return results.toString();
   }


}
