/* 
 * @author CodeGen 0.1 
 * create on Tue Nov 18 21:10:43 CST 2008
 * 
 * todo 
 */ 

package com.magic.crm.user.form;

import org.apache.struts.action.ActionForm;

/* 
 * this class is generated by codeGen 0.1 
 * create on Tue Nov 18 21:10:43 CST 2008
 * 
 * todo 
 */ 
public class S_payment_methodForm extends ActionForm{ 

	protected int id=0;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id=id;
	}


	protected String name="";
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name=name;
	}


	protected String description="";
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description=description;
	}


	protected String person_use="";
	public String getPerson_use() {
		return person_use;
	}
	public void setPerson_use(String person_use) {
		this.person_use=person_use;
	}


	protected String org_use="";
	public String getOrg_use() {
		return org_use;
	}
	public void setOrg_use(String org_use) {
		this.org_use=org_use;
	}


	protected String ref_dept="";
	public String getRef_dept() {
		return ref_dept;
	}
	public void setRef_dept(String ref_dept) {
		this.ref_dept=ref_dept;
	}


	protected String bank="";
	public String getBank() {
		return bank;
	}
	public void setBank(String bank) {
		this.bank=bank;
	}


	protected double discount=0;
	public double getDiscount() {
		return discount;
	}
	public void setDiscount(double discount) {
		this.discount=discount;
	}

} 