package com.magic.crm.user.form;


/**
 * <code>ActionForm</code> Class<br>
 * <br>
 * Autogenerated on 03/14/2003 01:39:32<br>
 * &nbsp;&nbsp;&nbsp; table = "pathright"
*
* @author Generator
*/
public class PathRightForm extends org.apache.struts.action.ActionForm
     implements java.io.Serializable {


   /**
    * The path attribute.
   */
   protected java.lang.String path = null;

   /**
    * Gets the path value.
   */
   public java.lang.String getPath() {
      return path;
   }

   /**
    * Sets the path value.
   */
   public void setPath(java.lang.String path) {
      this.path = path;
   }

   /**
    * The rightId attribute.
   */
   protected java.lang.String rightId = null;

   /**
    * Gets the rightId value.
   */
   public java.lang.String getRightId() {
      return rightId;
   }

   /**
    * Sets the rightId value.
   */
   public void setRightId(java.lang.String rightId) {
      this.rightId = rightId;
   }

   public void reset(org.apache.struts.action.ActionMapping mapping, javax.servlet.http.HttpServletRequest request) {
      path = null;
      rightId = null;
   }

   public String toString() {
      StringBuffer results = new StringBuffer();

      results.append(getClass().getName() + "\n");
      results.append("\tpath=" + path + "\n");
      results.append("\trightId=" + rightId + "\n");

      return results.toString();
   }


}
