package com.magic.crm.user.form;

/* 
 * @author CodeGen 0.1 
 * create on Sun Aug 24 20:59:23 CST 2008
 * 
 * todo 
 */ 

import java.util.ArrayList;

import org.apache.struts.action.ActionForm;

/* 
 * this class is generated by codeGen 0.1 
 * create on Sun Aug 24 20:59:23 CST 2008
 * 
 * todo 
 */ 
public class S_AREAForm extends ActionForm{ 

	protected ArrayList provs = new ArrayList();
	protected ArrayList citys = new ArrayList();
	
	
	/**
	 * @return the provs
	 */
	public ArrayList getProvs() {
		return provs;
	}
	/**
	 * @param provs the provs to set
	 */
	public void setProvs(ArrayList provs) {
		this.provs = provs;
	}
	/**
	 * @return the citys
	 */
	public ArrayList getCitys() {
		return citys;
	}
	/**
	 * @param citys the citys to set
	 */
	public void setCitys(ArrayList citys) {
		this.citys = citys;
	}


	protected String postcode = "";
	
	public String getPostcode() {
		return postcode;
	}
	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}


	protected String province="";
	protected String provinceName="";
	protected String city="";
	protected String cityName="";
	
	/**
	 * @return the province
	 */
	public String getProvince() {
		return province;
	}
	/**
	 * @param province the province to set
	 */
	public void setProvince(String province) {
		this.province = province;
	}
	/**
	 * @return the provinceName
	 */
	public String getProvinceName() {
		return provinceName;
	}
	/**
	 * @param provinceName the provinceName to set
	 */
	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}
	/**
	 * @return the city
	 */
	public String getCity() {
		return city;
	}
	/**
	 * @param city the city to set
	 */
	public void setCity(String city) {
		this.city = city;
	}
	/**
	 * @return the cityName
	 */
	public String getCityName() {
		return cityName;
	}
	/**
	 * @param cityName the cityName to set
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName;
	}


	protected String areacode="";
	public String getAreacode() {
		return areacode;
	}
	public void setAreacode(String areacode) {
		this.areacode=areacode;
	}


	protected String areaname="";
	public String getAreaname() {
		return areaname;
	}
	public void setAreaname(String areaname) {
		this.areaname=areaname;
	}


	protected String parentareacode="";
	public String getParentareacode() {
		return parentareacode;
	}
	public void setParentareacode(String parentareacode) {
		this.parentareacode=parentareacode;
	}


	protected int root=0;
	public int getRoot() {
		return root;
	}
	public void setRoot(int root) {
		this.root=root;
	}


	protected int zone=0;
	public int getZone() {
		return zone;
	}
	public void setZone(int zone) {
		this.zone=zone;
	}


	protected int is_express=0;
	public int getIs_express() {
		return is_express;
	}
	public void setIs_express(int is_express) {
		this.is_express=is_express;
	}

} 