package com.magic.crm.config.dao;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;



/**
 * Jdbc Bean Class<br>
 * <br>
 * Autogenerated on 03/17/2003 10:36:03<br>
 * &nbsp;&nbsp;&nbsp; table = "users"
*
* @author Generator
*/
public class SConfigKeysDAO implements java.io.Serializable {


   public static String getValueByKey(Connection con,String key) throws SQLException {
       PreparedStatement pstmt = null;
       ResultSet rs = null;
       String value = null;

       try {
          String sQuery = "select value from s_config_keys where key = ?";
          pstmt = con.prepareStatement(sQuery);

          pstmt.setString(1,key);

          rs = pstmt.executeQuery();

          if (rs.next()) {
          	value =rs.getString("value");
          } 
       } catch (SQLException e) {
         throw e;
       } finally {
          if (rs != null)
             try { rs.close(); } catch (Exception e) {}
          if (pstmt != null)
             try { pstmt.close(); } catch (Exception e) {}
       }
       return value;
   }
}