package com.magic.crm.user.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;

import com.magic.crm.user.entity.*;

/**
 * Jdbc Bean Class <br>
 * <br>
 * Autogenerated on 03/17/2003 10:36:03 <br>
 * &nbsp;&nbsp;&nbsp; table = "crm_rights"
 * 
 * @author Generator
 */
public class RightDAO implements java.io.Serializable {

    public com.magic.crm.user.entity.Right findByPrimaryKey(Connection con,
            com.magic.crm.user.entity.Right info) throws SQLException {
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            String sQuery = "SELECT rightId, rightName,parentId FROM crm_rights  ";
            pstmt = con.prepareStatement(sQuery);

            rs = pstmt.executeQuery();

            if (rs.next()) {
                info.setRightId(rs.getBigDecimal("rightId"));
                info.setRightName(rs.getString("rightName"));
                info.setParentId(rs.getBigDecimal("parentId"));
            } else {
                return null;
            }
        } catch (SQLException e) {
            throw e;
        } finally {
            if (rs != null)
                try {
                    rs.close();
                } catch (Exception e) {
                }
            if (pstmt != null)
                try {
                    pstmt.close();
                } catch (Exception e) {
                }
        }
        return info;
    }

    public Collection findAllRights(Connection con) throws SQLException {
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        Collection rightCol = new ArrayList();

        try {
            String sQuery = "SELECT rightId, rightName,parentId FROM crm_rights where parentid<>0 order by parentId";
            pstmt = con.prepareStatement(sQuery);

            rs = pstmt.executeQuery();

            while (rs.next()) {
                Right info = new Right();
                info.setRightId(rs.getBigDecimal("rightId"));
                info.setRightName(rs.getString("rightName"));
                info.setParentId(rs.getBigDecimal("parentId"));
                rightCol.add(info);
            }

            return rightCol;

        } catch (SQLException e) {
            throw e;
        } finally {
            if (rs != null)
                try {
                    rs.close();
                } catch (Exception e) {
                }
            if (pstmt != null)
                try {
                    pstmt.close();
                } catch (Exception e) {
                }
        }
    }

    public Collection findAllRights(Connection con, Right info)
            throws SQLException {
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        Collection rightCol = new ArrayList();

        try {
            String sQuery = "SELECT rightId, rightName,parentId FROM crm_rights ";
            pstmt = con.prepareStatement(sQuery);

            rs = pstmt.executeQuery();
            int i = 0;
            while (rs.next()) {

                info.setRightId(rs.getBigDecimal("rightId"));
                info.setRightName(rs.getString("rightName"));
                info.setParentId(rs.getBigDecimal("parentId"));
                info.setID(String.valueOf(i));
                rightCol.add(info);
                i++;
            }

            return rightCol;

        } catch (SQLException e) {
            throw e;
        } finally {
            if (rs != null)
                try {
                    rs.close();
                } catch (Exception e) {
                }
            if (pstmt != null)
                try {
                    pstmt.close();
                } catch (Exception e) {
                }
        }
    }

    public void insert(Connection con, com.magic.crm.user.entity.Right info)
            throws SQLException {
        PreparedStatement pstmt = null;

        try {
            String sQuery = "INSERT INTO crm_rights(rightId, rightName) VALUES(?, ?)";
            pstmt = con.prepareStatement(sQuery);

            pstmt.setBigDecimal(1, info.getRightId());
            pstmt.setString(2, info.getRightName());

            pstmt.execute();

        } catch (SQLException e) {
            throw e;
        } finally {
            if (pstmt != null)
                try {
                    pstmt.close();
                } catch (Exception e) {
                }
        }
    }

    public void update(Connection con, com.magic.crm.user.entity.Right info)
            throws SQLException {
        PreparedStatement pstmt = null;

        try {
            String sQuery = "UPDATE crm_rights SET rightId=?, rightName=? WHERE ";
            pstmt = con.prepareStatement(sQuery);

            pstmt.setBigDecimal(1, info.getRightId());
            pstmt.setString(2, info.getRightName());

            pstmt.execute();

        } catch (SQLException e) {
            throw e;
        } finally {
            if (pstmt != null)
                try {
                    pstmt.close();
                } catch (Exception e) {
                }
        }
    }

    public void delete(Connection con, com.magic.crm.user.entity.Right info)
            throws SQLException {
        PreparedStatement pstmt = null;

        try {
            String sQuery = "DELETE crm_rights WHERE ";
            pstmt = con.prepareStatement(sQuery);

            pstmt.execute();

        } catch (SQLException e) {
            throw e;
        } finally {
            if (pstmt != null)
                try {
                    pstmt.close();
                } catch (Exception e) {
                }
        }
    }

}
